// ... existing tool registry entries ...
  { href: '/all-units-converter', title: 'Unit Converter', icon: ArrowRightLeft, keywords: ['unit', 'convert', 'length', 'weight', 'temp', 'measure'], desc: 'Universal unit matrix.' },
];
// ... rest of file ...
